FROM node:18
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .
RUN yarn

RUN cp node_modules/lightningcss-linux-arm64-gnu/lightningcss.linux-arm64-gnu.node node_modules/lightningcss || :
RUN cp node_modules/lightningcss-linux-arm-gnueabihf/lightningcss.linux-arm-gnueabihf.node node_modules/lightningcss || :

COPY index.html .
RUN yarn build
